número_1= input('ingrese primer número:')
print('ingresaste el numero:',número_1)
número_2= input('ingrese segundo número:')
print('ingresaste el numero:',número_2)
if int(número_1) > int(número_2): print('el primer número es mayor')
else: print('el segundo número es el mayor')